version: "3.8"
services:
  mysql:
    image: mysql:latest
    ports:
      - "23306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}  # 데이터베이스 이름을 지정
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # 루트 비밀번호를 지정
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - mysql
    restart: always

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: always
