version: "3.8"
services:
  mysql:
    image: mysql:latest
    ports:
      - "23306:3306"
    environment:
      MYSQL_DATABASE: spaghettiDB
      MYSQL_ROOT_PASSWORD: ${PROD_DB_PASSWORD}
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - mysql
    restart: always

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: ${PROD_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${PROD_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${PROD_DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    restart: always
